/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        bg: '#1e0f13',
        surface: '#2c1b1f',
        'surface-lowest': '#180a0e',
        'surface-low': '#27171b',
        'surface-high': '#372529',
        'surface-highest': '#433034',
        'surface-bright': '#473438',
        primary: '#ff3385',
        'primary-container': '#ff4a8c',
        'primary-dim': '#ffb1c4',
        'on-primary': '#65002e',
        secondary: '#8a2be2',
        'secondary-container': '#7701d0',
        'secondary-light': '#dcb8ff',
        tertiary: '#5ee060',
        'tertiary-container': '#16a72e',
        error: '#ffb4ab',
        'error-container': '#93000a',
        outline: '#aa888f',
        'outline-variant': '#5b3f46',
        heading: '#ffffff',
        ink: '#f9dbe1',
        'ink-muted': '#e3bdc5',
      },
      fontFamily: {
        display: ['BeVietnamPro_700Bold'],
        heading: ['BeVietnamPro_700Bold'],
        title: ['BeVietnamPro_600SemiBold'],
        body: ['BeVietnamPro_400Regular'],
        medium: ['BeVietnamPro_500Medium'],
        label: ['BeVietnamPro_600SemiBold'],
      },
      borderRadius: {
        card: '24px',
      },
    },
  },
  plugins: [],
};
