"""add opponent community to challenges

Revision ID: 133af838fbe7
Revises: 82358ee59c4b
Create Date: 2026-07-22 15:43:48.734872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133af838fbe7'
down_revision: Union[str, Sequence[str], None] = '82358ee59c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('opponent_community_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_challenges_opponent_community_id'), 'challenges', ['opponent_community_id'], unique=False)
    op.create_foreign_key(None, 'challenges', 'communities', ['opponent_community_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'challenges', type_='foreignkey')
    op.drop_index(op.f('ix_challenges_opponent_community_id'), table_name='challenges')
    op.drop_column('challenges', 'opponent_community_id')
    # ### end Alembic commands ###
