"""create votes table

Revision ID: 2e0f8a57f4cd
Revises: c47a1b2e9f60
Create Date: 2026-07-22 13:30:21.214285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0f8a57f4cd'
down_revision: Union[str, Sequence[str], None] = 'c47a1b2e9f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('meme_id', sa.Uuid(), nullable=False),
    sa.Column('period_type', sa.Enum('day', 'week', 'month', name='competition_period_type'), nullable=False),
    sa.Column('period_key', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'meme_id', 'period_type', 'period_key', name='uq_votes_user_meme_period')
    )
    op.create_index(op.f('ix_votes_meme_id'), 'votes', ['meme_id'], unique=False)
    op.create_index(op.f('ix_votes_period_key'), 'votes', ['period_key'], unique=False)
    op.create_index(op.f('ix_votes_user_id'), 'votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_user_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_period_key'), table_name='votes')
    op.drop_index(op.f('ix_votes_meme_id'), table_name='votes')
    op.drop_table('votes')
    # ### end Alembic commands ###
