"""create memes, post_audiences, reactions, comments tables

Revision ID: 4fc0df6fbbf6
Revises: c8c3a3480b54
Create Date: 2026-07-21 14:50:07.292709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc0df6fbbf6'
down_revision: Union[str, Sequence[str], None] = 'c8c3a3480b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memes',
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('image_public_id', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memes_author_id'), 'memes', ['author_id'], unique=False)
    op.create_table('comments',
    sa.Column('meme_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_meme_id'), 'comments', ['meme_id'], unique=False)
    op.create_table('post_audiences',
    sa.Column('meme_id', sa.Uuid(), nullable=False),
    sa.Column('audience_type', sa.Enum('public', 'friends', name='post_audience_type'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meme_id', 'audience_type', name='uq_post_audience_meme_type')
    )
    op.create_index(op.f('ix_post_audiences_meme_id'), 'post_audiences', ['meme_id'], unique=False)
    op.create_table('reactions',
    sa.Column('meme_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meme_id', 'user_id', name='uq_reactions_meme_user')
    )
    op.create_index(op.f('ix_reactions_meme_id'), 'reactions', ['meme_id'], unique=False)
    op.create_index(op.f('ix_reactions_user_id'), 'reactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reactions_user_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_meme_id'), table_name='reactions')
    op.drop_table('reactions')
    op.drop_index(op.f('ix_post_audiences_meme_id'), table_name='post_audiences')
    op.drop_table('post_audiences')
    op.drop_index(op.f('ix_comments_meme_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_memes_author_id'), table_name='memes')
    op.drop_table('memes')
    # ### end Alembic commands ###
