"""add friend/community/engagement/competition notification types

Revision ID: 584f3b9c7195
Revises: fba995690df0
Create Date: 2026-08-31 17:57:50.061468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '584f3b9c7195'
down_revision: Union[str, Sequence[str], None] = 'fba995690df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_NEW_NOTIFICATION_TYPES = [
    "friend_request_received",
    "friend_request_accepted",
    "community_join_request",
    "community_join_approved",
    "community_join_rejected",
    "community_post_removed",
    "meme_comment_received",
    "meme_upvotes_received",
    "competition_won",
]


def upgrade() -> None:
    """Upgrade schema."""
    # Alembic autogenerate doesn't detect Postgres enum value additions — written by hand,
    # same precedent as 9c2a5e14d7f1_add_invited_membership_status.py. Safe inside this
    # migration's own transaction since nothing here *uses* the new values yet.
    for value in _NEW_NOTIFICATION_TYPES:
        op.execute(f"ALTER TYPE notification_type ADD VALUE IF NOT EXISTS '{value}'")

    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed `op.drop_table('imgflip_templates')` — that table is
    # pre-existing drift unrelated to this change (not modeled in SQLAlchemy at all), left
    # untouched here rather than dropped as an accidental side effect of this migration.
    #
    # `competition_period_type` was dropped by ff18f4b3fc3f's upgrade() (raw `DROP TYPE`,
    # bypassing SQLAlchemy's own state tracking) and is being reintroduced here. Explicit
    # raw CREATE, then the column type built as `postgresql.ENUM(..., create_type=False)`
    # (not bare `sa.Enum` - a generic `sa.Enum` doesn't reliably honor `create_type` and
    # still tries to emit its own CREATE TYPE, colliding with the one below) - same
    # pattern already used by 969bf629bf4c for this exact type.
    op.execute("CREATE TYPE competition_period_type AS ENUM ('day', 'week', 'month')")
    competition_period_type = postgresql.ENUM(
        "day", "week", "month", name="competition_period_type", create_type=False
    )
    op.create_table('competition_winner_notifications',
    sa.Column('period_type', competition_period_type, nullable=False),
    sa.Column('period_key', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_type', 'period_key', name='uq_competition_winner_notifications_period')
    )
    op.create_table('notification_cron_cursors',
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_cron_cursors')
    op.drop_table('competition_winner_notifications')
    # ### end Alembic commands ###
    op.execute('DROP TYPE IF EXISTS competition_period_type')

    # Postgres has no `ALTER TYPE ... DROP VALUE` — same documented limitation as
    # 9c2a5e14d7f1_add_invited_membership_status.py. No-op; rows using any of the new
    # values would need to be reassigned/deleted by hand before a real rollback past this.
