"""add performance indexes for feed, membership, friendship, challenge queries

Revision ID: 6b07283419b0
Revises: 969bf629bf4c
Create Date: 2026-07-23 14:29:46.720047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b07283419b0'
down_revision: Union[str, Sequence[str], None] = '969bf629bf4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_challenge_participants_user_id'), 'challenge_participants', ['user_id'], unique=False)
    op.create_index(op.f('ix_challenge_submissions_meme_id'), 'challenge_submissions', ['meme_id'], unique=False)
    op.create_index(op.f('ix_challenge_submissions_submitter_id'), 'challenge_submissions', ['submitter_id'], unique=False)
    op.create_index('ix_community_memberships_community_user_status', 'community_memberships', ['community_id', 'user_id', 'status'], unique=False)
    op.create_index('ix_friendships_addressee_status', 'friendships', ['addressee_id', 'status'], unique=False)
    op.create_index('ix_friendships_requester_status', 'friendships', ['requester_id', 'status'], unique=False)
    op.create_index('ix_memes_created_at_id', 'memes', ['created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memes_created_at_id', table_name='memes')
    op.drop_index('ix_friendships_requester_status', table_name='friendships')
    op.drop_index('ix_friendships_addressee_status', table_name='friendships')
    op.drop_index('ix_community_memberships_community_user_status', table_name='community_memberships')
    op.drop_index(op.f('ix_challenge_submissions_submitter_id'), table_name='challenge_submissions')
    op.drop_index(op.f('ix_challenge_submissions_meme_id'), table_name='challenge_submissions')
    op.drop_index(op.f('ix_challenge_participants_user_id'), table_name='challenge_participants')
    # ### end Alembic commands ###
