"""add community_id to templates

Revision ID: 74485aecff71
Revises: a37f7c9ea291
Create Date: 2026-07-21 18:26:37.928448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74485aecff71'
down_revision: Union[str, Sequence[str], None] = 'a37f7c9ea291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('community_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_templates_community_id'), 'templates', ['community_id'], unique=False)
    op.create_foreign_key(None, 'templates', 'communities', ['community_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_index(op.f('ix_templates_community_id'), table_name='templates')
    op.drop_column('templates', 'community_id')
    # ### end Alembic commands ###
