"""create challenges tables

Revision ID: 82358ee59c4b
Revises: 2e0f8a57f4cd
Create Date: 2026-07-22 14:41:00.385951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82358ee59c4b'
down_revision: Union[str, Sequence[str], None] = '2e0f8a57f4cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - manually reordered to break the
    # challenges <-> challenge_sides circular FK (winning_side_id added after both
    # tables exist, via a separate ALTER TABLE) ###
    op.create_table('challenges',
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('challenge_type', sa.Enum('intra_community', 'community_vs_community', name='challenge_type'), nullable=False),
    sa.Column('status', sa.Enum('setup', 'active', 'evaluated', name='challenge_status'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('winning_side_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_community_id'), 'challenges', ['community_id'], unique=False)
    op.create_table('challenge_sides',
    sa.Column('challenge_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'name', name='uq_challenge_side_name')
    )
    op.create_index(op.f('ix_challenge_sides_challenge_id'), 'challenge_sides', ['challenge_id'], unique=False)
    op.create_foreign_key(
        'fk_challenges_winning_side_id_challenge_sides',
        'challenges', 'challenge_sides', ['winning_side_id'], ['id'], ondelete='SET NULL'
    )
    op.create_table('badges',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('badge_type', sa.Enum('challenge_winner', name='badge_type'), nullable=False),
    sa.Column('challenge_id', sa.Uuid(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_user_id'), 'badges', ['user_id'], unique=False)
    op.create_table('challenge_participants',
    sa.Column('challenge_id', sa.Uuid(), nullable=False),
    sa.Column('side_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['side_id'], ['challenge_sides.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'user_id', name='uq_challenge_participant_user')
    )
    op.create_index(op.f('ix_challenge_participants_challenge_id'), 'challenge_participants', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_participants_side_id'), 'challenge_participants', ['side_id'], unique=False)
    op.create_table('challenge_submissions',
    sa.Column('challenge_id', sa.Uuid(), nullable=False),
    sa.Column('side_id', sa.Uuid(), nullable=False),
    sa.Column('submitter_id', sa.Uuid(), nullable=False),
    sa.Column('meme_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['side_id'], ['challenge_sides.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'meme_id', name='uq_challenge_submission_meme')
    )
    op.create_index(op.f('ix_challenge_submissions_challenge_id'), 'challenge_submissions', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_submissions_side_id'), 'challenge_submissions', ['side_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_submissions_side_id'), table_name='challenge_submissions')
    op.drop_index(op.f('ix_challenge_submissions_challenge_id'), table_name='challenge_submissions')
    op.drop_table('challenge_submissions')
    op.drop_index(op.f('ix_challenge_participants_side_id'), table_name='challenge_participants')
    op.drop_index(op.f('ix_challenge_participants_challenge_id'), table_name='challenge_participants')
    op.drop_table('challenge_participants')
    op.drop_index(op.f('ix_badges_user_id'), table_name='badges')
    op.drop_table('badges')
    op.drop_constraint('fk_challenges_winning_side_id_challenge_sides', 'challenges', type_='foreignkey')
    op.drop_index(op.f('ix_challenge_sides_challenge_id'), table_name='challenge_sides')
    op.drop_table('challenge_sides')
    op.drop_index(op.f('ix_challenges_community_id'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
