"""create meme_containers and container reactions comments votes tables

Revision ID: 969bf629bf4c
Revises: a31087eb8f96
Create Date: 2026-07-23 13:28:57.370645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '969bf629bf4c'
down_revision: Union[str, Sequence[str], None] = 'a31087eb8f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `competition_period_type` already exists (created by the `votes` table's migration) —
    # `container_votes.period_type` reuses it rather than creating a second enum type, so
    # this table creation must not attempt to CREATE TYPE it again.
    competition_period_type = postgresql.ENUM(
        "day", "week", "month", name="competition_period_type", create_type=False
    )

    op.create_table('meme_containers',
    sa.Column('submitter_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('instagram', name='container_platform'), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('metadata_status', sa.Enum('pending', 'ready', 'failed', name='container_metadata_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meme_containers_submitter_id'), 'meme_containers', ['submitter_id'], unique=False)
    op.create_table('container_comments',
    sa.Column('meme_container_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meme_container_id'], ['meme_containers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_container_comments_author_id'), 'container_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_container_comments_meme_container_id'), 'container_comments', ['meme_container_id'], unique=False)
    op.create_table('container_reactions',
    sa.Column('meme_container_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meme_container_id'], ['meme_containers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meme_container_id', 'user_id', name='uq_container_reactions_container_user')
    )
    op.create_index(op.f('ix_container_reactions_meme_container_id'), 'container_reactions', ['meme_container_id'], unique=False)
    op.create_index(op.f('ix_container_reactions_user_id'), 'container_reactions', ['user_id'], unique=False)
    op.create_table('container_votes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('meme_container_id', sa.Uuid(), nullable=False),
    sa.Column('period_type', competition_period_type, nullable=False),
    sa.Column('period_key', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meme_container_id'], ['meme_containers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'meme_container_id', 'period_type', 'period_key', name='uq_container_votes_user_container_period')
    )
    op.create_index(op.f('ix_container_votes_meme_container_id'), 'container_votes', ['meme_container_id'], unique=False)
    op.create_index(op.f('ix_container_votes_period_key'), 'container_votes', ['period_key'], unique=False)
    op.create_index(op.f('ix_container_votes_user_id'), 'container_votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_container_votes_user_id'), table_name='container_votes')
    op.drop_index(op.f('ix_container_votes_period_key'), table_name='container_votes')
    op.drop_index(op.f('ix_container_votes_meme_container_id'), table_name='container_votes')
    op.drop_table('container_votes')
    op.drop_index(op.f('ix_container_reactions_user_id'), table_name='container_reactions')
    op.drop_index(op.f('ix_container_reactions_meme_container_id'), table_name='container_reactions')
    op.drop_table('container_reactions')
    op.drop_index(op.f('ix_container_comments_meme_container_id'), table_name='container_comments')
    op.drop_index(op.f('ix_container_comments_author_id'), table_name='container_comments')
    op.drop_table('container_comments')
    op.drop_index(op.f('ix_meme_containers_submitter_id'), table_name='meme_containers')
    op.drop_table('meme_containers')
    # ### end Alembic commands ###
