"""create meme_sends table

Revision ID: a31087eb8f96
Revises: 133af838fbe7
Create Date: 2026-07-22 16:36:23.733389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a31087eb8f96'
down_revision: Union[str, Sequence[str], None] = '133af838fbe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meme_sends',
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('meme_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('delivered', 'pending', 'seen', name='meme_send_status'), nullable=False),
    sa.Column('reaction', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meme_sends_recipient_id'), 'meme_sends', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_meme_sends_sender_id'), 'meme_sends', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meme_sends_sender_id'), table_name='meme_sends')
    op.drop_index(op.f('ix_meme_sends_recipient_id'), table_name='meme_sends')
    op.drop_table('meme_sends')
    # ### end Alembic commands ###
