"""create friendships table

Revision ID: c8c3a3480b54
Revises: f8a6c1da5443
Create Date: 2026-07-21 12:54:28.901180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8c3a3480b54'
down_revision: Union[str, Sequence[str], None] = 'f8a6c1da5443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('addressee_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', name='friendship_status'), nullable=False),
    sa.Column('user_low', sa.Uuid(), sa.Computed('LEAST(requester_id, addressee_id)', persisted=True), nullable=False),
    sa.Column('user_high', sa.Uuid(), sa.Computed('GREATEST(requester_id, addressee_id)', persisted=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('requester_id <> addressee_id', name='ck_friendships_not_self'),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_low', 'user_high', name='uq_friendships_pair')
    )
    op.create_index(op.f('ix_friendships_addressee_id'), 'friendships', ['addressee_id'], unique=False)
    op.create_index(op.f('ix_friendships_requester_id'), 'friendships', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friendships_requester_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_addressee_id'), table_name='friendships')
    op.drop_table('friendships')
    # ### end Alembic commands ###
