"""add hashtags and open challenges

Phase 20. Adds first-class hashtags (`hashtags` + `meme_hashtags`) and the `open` challenge
shape: a platform-level challenge with no community, entered by posting with the tag it
reserves exclusively.

Written by hand rather than autogenerated — a concurrent session was mid-flight on other
models, and autogenerate would have swept their in-progress changes into this revision.

Note on the enum: Postgres forbids *using* a brand-new enum value in the transaction that
adds it (see .claude/memory/meme-feed.md), and this repo's env.py runs a whole upgrade in
one transaction. Adding `'open'` is safe here because nothing in this migration writes a
row with that value — only later application code does.

Revision ID: f4a7b2c9d813
Revises: e1d2c3b4a596
Create Date: 2026-08-06

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f4a7b2c9d813'
down_revision: Union[str, Sequence[str], None] = 'e1d2c3b4a596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'hashtags',
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('display_text', sa.String(length=100), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_hashtags_slug'), 'hashtags', ['slug'], unique=True)

    op.create_table(
        'meme_hashtags',
        sa.Column('meme_id', sa.Uuid(), nullable=False),
        sa.Column('hashtag_id', sa.Uuid(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('meme_id', 'hashtag_id', name='uq_meme_hashtag'),
    )
    op.create_index(op.f('ix_meme_hashtags_meme_id'), 'meme_hashtags', ['meme_id'], unique=False)
    op.create_index(
        op.f('ix_meme_hashtags_hashtag_id'), 'meme_hashtags', ['hashtag_id'], unique=False
    )

    op.execute("ALTER TYPE challenge_type ADD VALUE IF NOT EXISTS 'open'")

    # Open challenges belong to the platform, not to a community.
    op.alter_column('challenges', 'community_id', existing_type=sa.Uuid(), nullable=True)

    # Unique so a tag can only ever be reserved by one challenge — no squatting an active
    # competition. RESTRICT rather than CASCADE: deleting a tag out from under a live
    # challenge would orphan its only entry mechanism.
    op.add_column('challenges', sa.Column('hashtag_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_challenges_hashtag_id'), 'challenges', ['hashtag_id'], unique=True)
    op.create_foreign_key(
        'fk_challenges_hashtag_id_hashtags',
        'challenges',
        'hashtags',
        ['hashtag_id'],
        ['id'],
        ondelete='RESTRICT',
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('fk_challenges_hashtag_id_hashtags', 'challenges', type_='foreignkey')
    op.drop_index(op.f('ix_challenges_hashtag_id'), table_name='challenges')
    op.drop_column('challenges', 'hashtag_id')

    # Any open challenge must go before community_id can be NOT NULL again.
    op.execute("DELETE FROM challenges WHERE challenge_type = 'open'")
    op.alter_column('challenges', 'community_id', existing_type=sa.Uuid(), nullable=False)

    op.drop_index(op.f('ix_meme_hashtags_hashtag_id'), table_name='meme_hashtags')
    op.drop_index(op.f('ix_meme_hashtags_meme_id'), table_name='meme_hashtags')
    op.drop_table('meme_hashtags')
    op.drop_index(op.f('ix_hashtags_slug'), table_name='hashtags')
    op.drop_table('hashtags')

    # Postgres can't drop a single enum value; the type is left with 'open' unused, which
    # is harmless and reversible only by recreating the type.
